<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="7" failed="1" skipped="8">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-17T11:48:48 IST" name="ShopNow" finished-at="2024-03-17T11:53:15 IST" duration-ms="266382">
    <groups>
    </groups>
    <test started-at="2024-03-17T11:48:48 IST" name="ShopNow Test" finished-at="2024-03-17T11:53:15 IST" duration-ms="266382">
      <class name="com.shopnow.qa.tests.HomeTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.HomeTest@7d0b7e3c]" started-at="2024-03-17T11:48:49 IST" name="setup" finished-at="2024-03-17T11:48:55 IST" duration-ms="5679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyWebsiteLoadSuccessfully()[pri:0, instance:com.shopnow.qa.tests.HomeTest@7d0b7e3c]" started-at="2024-03-17T11:48:55 IST" name="verifyWebsiteLoadSuccessfully" finished-at="2024-03-17T11:49:03 IST" duration-ms="7801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWebsiteLoadSuccessfully -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.HomeTest@7d0b7e3c]" started-at="2024-03-17T11:49:03 IST" name="tearDown" finished-at="2024-03-17T11:49:03 IST" duration-ms="522" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.HomeTest -->
      <class name="com.shopnow.qa.tests.ShippingTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.ShippingTest@909217e]" started-at="2024-03-17T11:51:26 IST" name="setup" finished-at="2024-03-17T11:51:58 IST" duration-ms="32254" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.ShippingPage.roadToShippingPage(ShippingPage.java:111)
at com.shopnow.qa.tests.ShippingTest.setup(ShippingTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCompleteAddressDetails()[pri:0, instance:com.shopnow.qa.tests.ShippingTest@909217e]" started-at="2024-03-17T11:51:58 IST" name="verifyCompleteAddressDetails" finished-at="2024-03-17T11:51:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.ShippingPage.roadToShippingPage(ShippingPage.java:111)
at com.shopnow.qa.tests.ShippingTest.setup(ShippingTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCompleteAddressDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.ShippingTest@909217e]" started-at="2024-03-17T11:51:58 IST" name="tearDown" finished-at="2024-03-17T11:51:58 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.ShippingTest -->
      <class name="com.shopnow.qa.tests.CheckOutTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.CheckOutTest@5afa3c9]" started-at="2024-03-17T11:50:06 IST" name="setup" finished-at="2024-03-17T11:50:45 IST" duration-ms="39389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCorrectProduchAddedInCart()[pri:1, instance:com.shopnow.qa.tests.CheckOutTest@5afa3c9]" started-at="2024-03-17T11:50:45 IST" name="verifyCorrectProduchAddedInCart" finished-at="2024-03-17T11:50:47 IST" duration-ms="1519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCorrectProduchAddedInCart -->
        <test-method signature="verifyToPlaceAnOrder()[pri:2, instance:com.shopnow.qa.tests.CheckOutTest@5afa3c9]" started-at="2024-03-17T11:50:47 IST" name="verifyToPlaceAnOrder" finished-at="2024-03-17T11:50:50 IST" duration-ms="3668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyToPlaceAnOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.CheckOutTest@5afa3c9]" started-at="2024-03-17T11:50:50 IST" name="tearDown" finished-at="2024-03-17T11:50:51 IST" duration-ms="784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.CheckOutTest -->
      <class name="com.shopnow.qa.tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.LoginTest@72035809]" started-at="2024-03-17T11:50:51 IST" name="setup" finished-at="2024-03-17T11:51:22 IST" duration-ms="30532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyValidEmailidAndPassword()[pri:0, instance:com.shopnow.qa.tests.LoginTest@72035809]" started-at="2024-03-17T11:51:22 IST" name="verifyValidEmailidAndPassword" finished-at="2024-03-17T11:51:25 IST" duration-ms="2947" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.tests.LoginTest.verifyValidEmailidAndPassword(LoginTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyValidEmailidAndPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.LoginTest@72035809]" started-at="2024-03-17T11:51:25 IST" name="tearDown" finished-at="2024-03-17T11:51:26 IST" duration-ms="568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.LoginTest -->
      <class name="com.shopnow.qa.tests.SearchTest">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com.shopnow.qa.tests.SearchTest@5f049ea1]" started-at="2024-03-17T11:49:03 IST" name="Setup" finished-at="2024-03-17T11:49:14 IST" duration-ms="11084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="verifySearchValidProductName()[pri:1, instance:com.shopnow.qa.tests.SearchTest@5f049ea1]" started-at="2024-03-17T11:49:14 IST" name="verifySearchValidProductName" finished-at="2024-03-17T11:49:25 IST" duration-ms="10216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearchValidProductName -->
        <test-method signature="verifyToClickOnSearchResultProduct()[pri:2, instance:com.shopnow.qa.tests.SearchTest@5f049ea1]" started-at="2024-03-17T11:49:25 IST" name="verifyToClickOnSearchResultProduct" finished-at="2024-03-17T11:49:30 IST" depends-on-methods="com.shopnow.qa.tests.SearchTest.verifySearchValidProductName" duration-ms="5867" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyToClickOnSearchResultProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.SearchTest@5f049ea1]" started-at="2024-03-17T11:49:30 IST" name="tearDown" finished-at="2024-03-17T11:49:31 IST" duration-ms="673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.SearchTest -->
      <class name="com.shopnow.qa.tests.OrderSummaryTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:51:58 IST" name="setup" finished-at="2024-03-17T11:52:37 IST" duration-ms="39552" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCorrectProductAddedInSummary()[pri:1, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:37 IST" name="verifyCorrectProductAddedInSummary" finished-at="2024-03-17T11:52:37 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCorrectProductAddedInSummary -->
        <test-method signature="verifyQuantiyOfProduct()[pri:2, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:37 IST" name="verifyQuantiyOfProduct" finished-at="2024-03-17T11:52:37 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuantiyOfProduct -->
        <test-method signature="verifyPriceAndRemoveButton()[pri:3, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:37 IST" name="verifyPriceAndRemoveButton" finished-at="2024-03-17T11:52:37 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPriceAndRemoveButton -->
        <test-method signature="VerifyFunctionalityOfContinueButtonInOrderSummary()[pri:4, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:37 IST" name="VerifyFunctionalityOfContinueButtonInOrderSummary" finished-at="2024-03-17T11:52:37 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyFunctionalityOfContinueButtonInOrderSummary -->
        <test-method signature="verifyAcceptAndContinueButton()[pri:5, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:37 IST" name="verifyAcceptAndContinueButton" finished-at="2024-03-17T11:52:37 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAcceptAndContinueButton -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.OrderSummaryTest@18271936]" started-at="2024-03-17T11:52:38 IST" name="tearDown" finished-at="2024-03-17T11:52:38 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.OrderSummaryTest -->
      <class name="com.shopnow.qa.tests.ProductTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.ProductTest@72cc7e6f]" started-at="2024-03-17T11:49:31 IST" name="setup" finished-at="2024-03-17T11:49:48 IST" duration-ms="16893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="VerifyPincodeFieldAndCheckButton()[pri:1, instance:com.shopnow.qa.tests.ProductTest@72cc7e6f]" started-at="2024-03-17T11:49:48 IST" name="VerifyPincodeFieldAndCheckButton" finished-at="2024-03-17T11:49:59 IST" duration-ms="10496" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyPincodeFieldAndCheckButton -->
        <test-method signature="verifyProductAddToBag()[pri:2, instance:com.shopnow.qa.tests.ProductTest@72cc7e6f]" started-at="2024-03-17T11:49:59 IST" name="verifyProductAddToBag" finished-at="2024-03-17T11:50:05 IST" depends-on-methods="com.shopnow.qa.tests.ProductTest.VerifyPincodeFieldAndCheckButton" duration-ms="6632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductAddToBag -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.ProductTest@72cc7e6f]" started-at="2024-03-17T11:50:05 IST" name="tearDown" finished-at="2024-03-17T11:50:06 IST" duration-ms="615" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.ProductTest -->
      <class name="com.shopnow.qa.tests.PaymentTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shopnow.qa.tests.PaymentTest@606e4010]" started-at="2024-03-17T11:52:38 IST" name="setup" finished-at="2024-03-17T11:53:14 IST" duration-ms="36903" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.PaymentPage.roadToPayment(PaymentPage.java:92)
at com.shopnow.qa.tests.PaymentTest.setup(PaymentTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyByClickingCreditCardRadioButton()[pri:1, instance:com.shopnow.qa.tests.PaymentTest@606e4010]" started-at="2024-03-17T11:53:14 IST" name="verifyByClickingCreditCardRadioButton" finished-at="2024-03-17T11:53:14 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.PaymentPage.roadToPayment(PaymentPage.java:92)
at com.shopnow.qa.tests.PaymentTest.setup(PaymentTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyByClickingCreditCardRadioButton -->
        <test-method signature="verifyCompleteDetailsOfCards()[pri:2, instance:com.shopnow.qa.tests.PaymentTest@606e4010]" started-at="2024-03-17T11:53:15 IST" name="verifyCompleteDetailsOfCards" finished-at="2024-03-17T11:53:15 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error detected on the page: 'Something's not right. Please try again.']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.PaymentPage.roadToPayment(PaymentPage.java:92)
at com.shopnow.qa.tests.PaymentTest.setup(PaymentTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCompleteDetailsOfCards -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shopnow.qa.tests.PaymentTest@606e4010]" started-at="2024-03-17T11:53:15 IST" name="tearDown" finished-at="2024-03-17T11:53:15 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shopnow.qa.tests.PaymentTest -->
    </test> <!-- ShopNow Test -->
  </suite> <!-- ShopNow -->
</testng-results>
