<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KrazY" failures="1" tests="6" name="com.shopnow.qa.tests.OrderSummaryTest" time="39.552" errors="0" timestamp="2024-03-17T11:53:18 IST" skipped="5">
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="setup" time="39.552">
    <failure message="Error detected on the page: &#039;Something&#039;s not right. Please try again.&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error detected on the page: 'Something's not right. Please try again.'
at org.testng.Assert.fail(Assert.java:111)
at com.shopnow.qa.pages.LoginPage.enterEmailid(LoginPage.java:57)
at com.shopnow.qa.pages.OrderSummaryPage.roadToOrderSummary(OrderSummaryPage.java:93)
at com.shopnow.qa.tests.OrderSummaryTest.setup(OrderSummaryTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- setup -->
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="verifyCorrectProductAddedInSummary" time="0.000">
    <skipped/>
  </testcase> <!-- verifyCorrectProductAddedInSummary -->
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="verifyQuantiyOfProduct" time="0.000">
    <skipped/>
  </testcase> <!-- verifyQuantiyOfProduct -->
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="verifyPriceAndRemoveButton" time="0.000">
    <skipped/>
  </testcase> <!-- verifyPriceAndRemoveButton -->
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="VerifyFunctionalityOfContinueButtonInOrderSummary" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyFunctionalityOfContinueButtonInOrderSummary -->
  <testcase classname="com.shopnow.qa.tests.OrderSummaryTest" name="verifyAcceptAndContinueButton" time="0.000">
    <skipped/>
  </testcase> <!-- verifyAcceptAndContinueButton -->
</testsuite> <!-- com.shopnow.qa.tests.OrderSummaryTest -->
